### ISSUE TITLE
We need docker version!

### ISSUE THREAD

**Issue by DangGwanHou** [lwQin/PortMonitor#1]
Hello, lwQin ,
I tried to convert your project into Linux version and run it on docker, but my personal technical ability is insufficient. 
Sincerely hope that project will update a Dockerfile, thank you!

**Comment by lwQin** [comment]
@DangGwanHou Please use [uptime-kuma](https://github.com/louislam/uptime-kuma) to instead of this project

**Comment by DangGwanHou** [comment]
thanks for recommendation
